language: r
cache: packages
dist: trusty

r_github_packages:
  - ropensci/crul

addons:
  apt:
    packages: oracle-java8-set-default

env:
  global:
    secure: H5kkOKDCSt3AUreH4dCGFNs053LzlkTUnxumw8T1WvaoKarPNp26BkuD/v2jepP7I5D32GePbypJkAsnf7//axwTv+5pCg+Jvp3QXqVInF7L3firSnMhZYaT103sGoQfirSRR36t8Fs18r+Z5HIMajiQtthcwUT1MsdsOhsPxNg=

matrix:
  include:
    - os: linux
      r: release
      env: ES_VERSION=1.0.0
    - os: linux
      r: release
      env: ES_VERSION=1.4.0
    - os: linux
      r: release
      env: ES_VERSION=1.7.2
    - os: linux
      r: release
      env: ES_VERSION=2.0.0
    - os: linux
      r: release
      env: ES_VERSION=2.3.0
    - os: linux
      r: release
      env: ES_VERSION=5.0.0
    - os: linux
      r: release
      env: ES_VERSION=5.5.0
    - os: linux
      r: release
      env: ES_VERSION=6.0.0
    - os: linux
      r: release
      env: ES_VERSION=6.5.3
    - os: linux
      r: release
      env: ES_VERSION=7.5.1 R_CODECOV=true

r_binary_packages:
  - covr 

before_install:
  - case "$ES_VERSION" in
    "") ;;

    "1.0.0")
      export ES_VERSION=1.0.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "1.4.0")
      export ES_VERSION=1.4.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "1.7.2")
      export ES_VERSION=1.7.2 ;
      curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "2.0.0")
      export ES_VERSION=2.0.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "2.3.0")
      export ES_VERSION=2.3.0 ;
      curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/$ES_VERSION/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "5.0.0")
      export ES_VERSION=5.0.0 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "5.5.0")
      export ES_VERSION=5.5.0 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.0.0")
      export ES_VERSION=6.0.0 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "6.5.3")
      export ES_VERSION=6.5.3 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;

    "7.5.1")
      export ES_VERSION=7.5.1 ;
      curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.deb && sudo dpkg -i --force-confnew elasticsearch-$ES_VERSION.deb && sudo service elasticsearch start
      ;;
   esac

  - sleep 3
  - sudo service elasticsearch status

after_success:
- if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: Mv3lFHkQvaPt1GAkAtdIsEvW9c0gSHhgLE5rx4u3Ex1gZYdCOFciimT8RcrqUi9EUMZ2xaqPPQYW189PGZFnjvjmuCfOUsXRxMvvZytjcjSagEuNKrRGKLBBXd4pSDqVtZTgTihkOyxfHSWGG7kGvZhan8sCmKNnun7d0BjmmgQ=
